version: "3.9"
services:
  backend:
    build: ./WebBackEnd/
    ports:
      - "5000:5000"
  backend1:
    build: ./WebBackEnd/
    ports:
      - "5001:5001"
  backend2:
    build: ./WebBackEnd/
    ports:
      - "5002:5002"
  frontend:
    build: ./Proxy/
    depends_on:
      - backend
      - backend1
      - backend2
    ports:
      - "4000:4000"