version: '3'

services:
    nodenetcore:
      build: .
      ports:
        - "4200:4200"
      volumes: 
        - "./project:/project"
       
volumes:
  project:


# https://anytimesnotes.com/archives/246