version: '3'
#https://www.youtube.com/watch?v=RDBifWtZeY0
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - wordpress
    restart: always
    environment:
      DOMAINS: 'localhost -> http://wordpress:80'   # コンテナ内のURLへリダイレクト
      STAGE: 'local' # Don't use production until staging works
      # FORCE_RENEW: 'true'

  wordpress:
    # url : http://{domain:port}/wp-admin/
    depends_on:
      - db
    #image: wordpress:latest
    build: .
    ports:
      - '80'
    container_name: wordpress
    volumes:
      - ./volume/wordpress/html:/var/www/html
      - ./volume/wordpress/conf.d:/usr/local/etc/php/conf.d/php.ini
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  db:
    image: mysql:5.7
    volumes:
      - ./volume/mysql/:/var/lib/mysql
    restart: always
    container_name: db_mysql5_7
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress