version: '3'
#https://www.youtube.com/watch?v=RDBifWtZeY0
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - wordpress
    restart: always
    environment:
      DOMAINS: 'localhost -> http://wordpress:80'
      STAGE: 'local' # Don't use production until staging works
      # FORCE_RENEW: 'true'

  wordpress:
    image: wordpress
    links:
      - db:mysql

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 'password!'